// src/react/Annotator.tsx
/**
 * Annota React - Annotator Component
 * OpenSeadragon annotator wrapper
 */

import { useEffect, ReactNode } from 'react';
import OpenSeadragon from 'openseadragon';
import {
  createOpenSeadragonAnnotator,
  type OpenSeadragonAnnotatorOptions,
  type OpenSeadragonAnnotator,
} from '../adapters/openseadragon/annotator';
import { useSetAnnotator } from './Provider';

/**
 * Annotator props
 */
export interface AnnotatorProps extends Omit<OpenSeadragonAnnotatorOptions, 'store'> {
  viewer: OpenSeadragon.Viewer | undefined;
  children?: ReactNode;
}

/**
 * Annotator
 * Creates and manages annotator lifecycle
 */
export function Annotator({ viewer, children, ...options }: AnnotatorProps) {
  const setAnnotator = useSetAnnotator();

  useEffect(() => {
    if (!viewer || !viewer.canvas) return;

    let cancelled = false;
    let annotatorInstance: OpenSeadragonAnnotator | undefined;

    createOpenSeadragonAnnotator(viewer, options).then(annotator => {
      if (cancelled) {
        annotator.destroy();
        return;
      }
      annotatorInstance = annotator;
      setAnnotator(annotator);
    });

    return () => {
      cancelled = true;
      if (annotatorInstance) {
        annotatorInstance.destroy();
      }
      setAnnotator(undefined);
    };
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [viewer]); // Only depend on viewer

  return <>{children}</>;
}

// src/svelte/components/Annotator.svelte
<script lang="ts">
  import { untrack } from "svelte";
  import type OpenSeadragon from "openseadragon";
  import {
    createOpenSeadragonAnnotator,
    type OpenSeadragonAnnotatorOptions,
    type OpenSeadragonAnnotator,
  } from "../../adapters/openseadragon/annotator";
  import { setAnnotator } from "../annotator";

  interface Props extends Omit<OpenSeadragonAnnotatorOptions, "store"> {
    viewer: OpenSeadragon.Viewer | undefined;
    children?: import("svelte").Snippet;
    [key: string]: any; // Allow other props for options
  }

  let { viewer, children, ...options }: Props = $props();

  const setAnnotatorFn = setAnnotator();
  let annotatorInstance: OpenSeadragonAnnotator | undefined = undefined;

  $effect(() => {
    if (!viewer || !viewer.canvas) return;

    let cancelled = false;

    // Untrack options so we only re-init when viewer changes, matching React behavior
    const opts = untrack(() => options) as OpenSeadragonAnnotatorOptions;

    createOpenSeadragonAnnotator(viewer, opts).then((annotator) => {
      if (cancelled) {
        annotator.destroy();
        return;
      }
      annotatorInstance = annotator;
      setAnnotatorFn(annotator);
    });

    return () => {
      cancelled = true;
      if (annotatorInstance) {
        annotatorInstance.destroy();
        annotatorInstance = undefined;
      }
      setAnnotatorFn(undefined);
    };
  });
</script>

{@render children?.()}
