// src/react/Viewer.tsx
/**
 * Annota React - Viewer Component
 * OpenSeadragon viewer wrapper
 */

import { useEffect, useRef, forwardRef, useImperativeHandle } from 'react';
import OpenSeadragon from 'openseadragon';

/**
 * Viewer props
 */
export interface ViewerProps {
  className?: string;
  style?: React.CSSProperties;
  options: OpenSeadragon.Options;
  onViewerReady?: (viewer: OpenSeadragon.Viewer) => void;
}

/**
 * Viewer
 * Creates and manages OpenSeadragon viewer lifecycle
 */
export const Viewer = forwardRef<OpenSeadragon.Viewer | undefined, ViewerProps>(
  ({ className, style, options, onViewerReady }, ref) => {
    const elementRef = useRef<HTMLDivElement>(null);
    const viewerRef = useRef<OpenSeadragon.Viewer | undefined>(undefined);

    useImperativeHandle(ref, () => viewerRef.current, []);

    // Create viewer once on mount
    useEffect(() => {
      if (!elementRef.current || viewerRef.current) return;

      // Sensible performance defaults; user-provided options override these
      const perfDefaults: Partial<OpenSeadragon.Options> = {
        useCanvas: true,
        immediateRender: true,
        alwaysBlend: false,
        blendTime: 0.05,
        animationTime: 0.2,
        imageLoaderLimit: 16,
        maxImageCacheCount: 512,
        preload: true,
        timeout: 120000,
        preserveImageSizeOnResize: true,
        gestureSettingsMouse: {
          clickToZoom: false,
          dblClickToZoom: false,
        } as any,
      };

      const viewer = OpenSeadragon({
        ...perfDefaults,
        ...options,
        element: elementRef.current,
      });

      viewerRef.current = viewer;
      onViewerReady?.(viewer);

      return () => {
        viewer.destroy();
        viewerRef.current = undefined;
      };
      // eslint-disable-next-line react-hooks/exhaustive-deps
    }, []); // Only create viewer once on mount

    // Update tile source when options.tileSources changes
    useEffect(() => {
      const viewer = viewerRef.current;
      if (!viewer || !options.tileSources) return;

      // Use viewer.open() to update tile source without recreating viewer
      // This is much faster than destroying and recreating the entire viewer
      viewer.open(options.tileSources);
    }, [options.tileSources]);

    return (
      <div
        ref={elementRef}
        className={className}
        style={{ ...style, isolation: 'isolate' }}
      />
    );
  }
);

Viewer.displayName = 'Viewer';

// src/svelte/components/Viewer.svelte
<script lang="ts">
  import { untrack } from "svelte";
  import type OpenSeadragon from "openseadragon";

  interface Props {
    class?: string;
    style?: string;
    options: OpenSeadragon.Options;
    onViewerReady?: (viewer: OpenSeadragon.Viewer) => void;
  }

  let { class: className, style, options, onViewerReady }: Props = $props();

  let element: HTMLDivElement;
  let viewer: OpenSeadragon.Viewer | undefined = $state(undefined);

  export function getViewer() {
    return viewer;
  }

  $effect(() => {
    if (!element || viewer || typeof window === 'undefined') return;

    // Dynamic import to avoid SSR issues
    import('openseadragon').then((OpenSeadragon) => {
      if (!element || viewer) return; // Check again after async import

      const perfDefaults: Partial<OpenSeadragon.Options> & { drawer?: string } = {
        drawer: "webgl",
        immediateRender: true,
        alwaysBlend: false,
        blendTime: 0.05,
        animationTime: 0.2,
        imageLoaderLimit: 16,
        maxImageCacheCount: 512,
        preload: true,
        timeout: 120000,
        preserveImageSizeOnResize: true,
        smoothTileEdgesMinZoom: Infinity,
        constrainDuringPan: true,
        visibilityRatio: 1.0,
        minZoomImageRatio: 0.8,
        maxZoomPixelRatio: 10,
        gestureSettingsMouse: {
          clickToZoom: false,
          dblClickToZoom: false,
        } as any,
      };

      const opts = untrack(() => options);

      const v = OpenSeadragon.default({
        ...perfDefaults,
        ...opts,
        element: element,
      });

      viewer = v;
      untrack(() => onViewerReady?.(v));
    });

    return () => {
      if (viewer) {
        viewer.destroy();
        viewer = undefined;
      }
    };
  });

  $effect(() => {
    if (!viewer || !options.tileSources) return;
    viewer.open(options.tileSources);
  });
</script>

<div
  bind:this={element}
  class={className}
  style="{style ? style + ';' : ''} isolation: isolate;"
></div>
