// docs/src/lib/components/playground/layer-panel.svelte
<script lang="ts">
  import {
    Eye,
    EyeOff,
    Lock,
    Unlock,
    Star,
    Download,
    Layers,
  } from "lucide-svelte";
  import { toastSuccess, toastError, toastInfo } from "$lib/services/toast";
  import { layerManager, getAnnotator, type Annotation } from "annota/svelte";
  import { exportMasksToPng } from "annota";
  import Button from "$lib/components/ui/Button.svelte";
  import { cn } from "$lib/utils";

  interface Props {
    trigger?: any;
    activeLayerId?: string;
    onActiveLayerChange?: (layerId: string) => void;
    imageVisible?: boolean;
    onImageVisibleChange?: (visible: boolean) => void;
  }

  let {
    trigger,
    activeLayerId,
    onActiveLayerChange,
    imageVisible = true,
    onImageVisibleChange,
  }: Props = $props();

  const getAnnotatorFn = getAnnotator();
  const annotator = $derived(getAnnotatorFn());
  const layerManagerInstance = layerManager();

  let dropdownOpen = $state(false);

  async function handleExportLayer(layerId: string, layerName: string) {
    if (!annotator) return;

    try {
      const layer = annotator.getLayer(layerId);
      if (!layer) {
        toastError("Layer not found");
        return;
      }

      const allAnnotations = annotator.state.store.all();
      const layerAnnotations = allAnnotations.filter((ann: Annotation) => {
        if (!layer.filter) return false;
        return layer.filter(ann);
      });

      if (layerAnnotations.length === 0) {
        toastInfo("No annotations in this layer to export");
        return;
      }

      if (!annotator.viewer) {
        toastError("Viewer not available");
        return;
      }

      const tiledImage = annotator.viewer.world.getItemAt(0);
      if (!tiledImage) {
        toastError("No image loaded");
        return;
      }

      const width = tiledImage.source.dimensions.x;
      const height = tiledImage.source.dimensions.y;

      toastInfo("Exporting mask layer...");
      const pngData = await exportMasksToPng(layerAnnotations, width, height);

      const blob = new Blob([pngData], { type: "image/png" });
      const url = URL.createObjectURL(blob);
      const link = document.createElement("a");
      link.href = url;
      link.download = `${layerName.replace(/\s+/g, "_")}_mask.png`;
      document.body.appendChild(link);
      link.click();
      document.body.removeChild(link);
      URL.revokeObjectURL(url);

      toastSuccess(`Exported ${layerAnnotations.length} mask(s) to PNG`);
    } catch (error) {
      console.error("Failed to export layer:", error);
      toastError("Failed to export layer");
    }
  }

  const sortedLayers = $derived(
    [...layerManagerInstance.layers]
      .filter((layer) => layer.id !== "image")
      .sort((a, b) => b.zIndex - a.zIndex)
  );
</script>

<div class="relative">
  {#if trigger}
    <button
      onclick={() => (dropdownOpen = !dropdownOpen)}
      class="w-9 h-9 p-1 hover:bg-slate-100 dark:hover:bg-slate-800 rounded transition-colors"
      title="Layers"
    >
      <Layers class="w-4 h-4" />
    </button>
  {/if}

  {#if dropdownOpen}
    <div
      class="absolute left-12 top-0 z-50 w-[320px] rounded-lg border border-slate-200 dark:border-slate-800 bg-white dark:bg-slate-950 shadow-lg"
      onclick={(e) => e.stopPropagation()}
      onkeydown={(e) => {
        if (e.key === "Escape") {
          dropdownOpen = false;
        }
      }}
      role="dialog"
      aria-label="Layers panel"
      tabindex="0"
    >
      <!-- Header -->
      <div
        class="flex items-center justify-between px-4 py-3 border-b border-slate-200 dark:border-slate-800"
      >
        <h3 class="text-sm font-semibold">Layers</h3>
        <button
          type="button"
          onclick={() => (dropdownOpen = false)}
          class="text-slate-500 hover:text-slate-700 dark:hover:text-slate-300"
          aria-label="Close layers panel"
        >
          ×
        </button>
      </div>

      <!-- Layer List -->
      <div class="max-h-[400px] overflow-y-auto">
        <!-- Image Layer -->
        <div
          class="px-4 py-2 bg-slate-50 dark:bg-slate-900/50 border-b border-slate-200 dark:border-slate-800"
        >
          <div class="flex items-center gap-2">
            <button
              onclick={() => onImageVisibleChange?.(!imageVisible)}
              class="p-1 hover:bg-slate-200 dark:hover:bg-slate-700 rounded transition-colors"
              title={imageVisible ? "Hide image" : "Show image"}
            >
              {#if imageVisible}
                <Eye class="w-4 h-4 text-blue-500" />
              {:else}
                <EyeOff class="w-4 h-4 text-slate-400" />
              {/if}
            </button>
            <span class="flex-1 text-sm font-semibold">Image</span>
            <span class="text-xs text-slate-500">Background</span>
          </div>
        </div>

        <!-- Annotation Layers -->
        {#if sortedLayers.length === 0}
          <div class="px-4 py-6 text-center text-sm text-slate-500">
            No annotation layers
          </div>
        {:else}
          <div class="py-1">
            {#each sortedLayers as layer (layer.id)}
              {@const isActive = activeLayerId === layer.id}
              <div
                class={cn(
                  "px-3 py-2 hover:bg-slate-50 dark:hover:bg-slate-800/50 transition-colors group relative",
                  isActive && "bg-slate-100 dark:bg-slate-800"
                )}
              >
                {#if isActive}
                  <div
                    class="absolute left-0 top-0 bottom-0 w-1 bg-blue-500"
                  ></div>
                {/if}

                <div class="flex items-center gap-2 mb-2">
                  <button
                    onclick={() => onActiveLayerChange?.(layer.id)}
                    class="p-1 hover:bg-slate-200 dark:hover:bg-slate-700 rounded transition-colors"
                    title={isActive ? "Active layer" : "Set as active layer"}
                  >
                    <Star
                      class={cn(
                        "w-4 h-4",
                        isActive
                          ? "text-blue-500 fill-blue-500"
                          : "text-slate-400 hover:text-slate-600 dark:hover:text-slate-300"
                      )}
                    />
                  </button>

                  <button
                    onclick={() =>
                      layerManagerInstance.setLayerVisibility(
                        layer.id,
                        !layer.visible
                      )}
                    class="p-1 hover:bg-slate-200 dark:hover:bg-slate-700 rounded transition-colors"
                    title={layer.visible ? "Hide layer" : "Show layer"}
                  >
                    {#if layer.visible}
                      <Eye class="w-4 h-4 text-blue-500" />
                    {:else}
                      <EyeOff class="w-4 h-4 text-slate-400" />
                    {/if}
                  </button>

                  <button
                    onclick={() =>
                      layerManagerInstance.setLayerLocked(
                        layer.id,
                        !layer.locked
                      )}
                    class="p-1 hover:bg-slate-200 dark:hover:bg-slate-700 rounded transition-colors"
                    title={layer.locked ? "Unlock layer" : "Lock layer"}
                  >
                    {#if layer.locked}
                      <Lock class="w-4 h-4 text-orange-500" />
                    {:else}
                      <Unlock class="w-4 h-4 text-slate-400" />
                    {/if}
                  </button>

                  <span
                    class={cn(
                      "flex-1 text-sm truncate",
                      isActive &&
                        "text-blue-600 dark:text-blue-400 font-semibold"
                    )}
                  >
                    {layer.name}
                  </span>

                  {#if layer.id === "positive-masks" || layer.id === "negative-masks"}
                    <button
                      onclick={() => handleExportLayer(layer.id, layer.name)}
                      class="p-1 hover:bg-green-50 dark:hover:bg-green-950/20 rounded transition-colors"
                      title="Export layer as PNG mask"
                    >
                      <Download
                        class="w-4 h-4 text-green-600 dark:text-green-500"
                      />
                    </button>
                  {/if}
                </div>

                <!-- Opacity Slider -->
                <div class="flex items-center gap-2 ml-10">
                  <span class="text-xs text-slate-500 w-16">Opacity:</span>
                  <input
                    type="range"
                    min="0"
                    max="1"
                    step="0.1"
                    value={layer.opacity}
                    oninput={(e) =>
                      layerManagerInstance.setLayerOpacity(
                        layer.id,
                        parseFloat(e.currentTarget.value)
                      )}
                    class="flex-1 h-1 bg-slate-300 dark:bg-slate-600 rounded-lg appearance-none cursor-pointer"
                  />
                  <span class="text-xs text-slate-500 w-8 text-right">
                    {Math.round(layer.opacity * 100)}%
                  </span>
                </div>
              </div>
            {/each}
          </div>
        {/if}
      </div>
    </div>
  {/if}
</div>

// examples/demo/src/components/layer-panel.tsx
'use client';

import { useState } from 'react';
import { useLayerManager } from 'annota';
import { Eye, EyeOff, Lock, Unlock, Plus, X, Star } from 'lucide-react';
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuSeparator,
  DropdownMenuTrigger,
} from '@/components/ui/dropdown-menu';

interface LayerPanelProps {
  trigger: React.ReactNode;
  activeLayerId?: string;
  onActiveLayerChange?: (layerId: string) => void;
  imageVisible?: boolean;
  onImageVisibleChange?: (visible: boolean) => void;
}

export function LayerPanel({
  trigger,
  activeLayerId,
  onActiveLayerChange,
  imageVisible = true,
  onImageVisibleChange,
}: LayerPanelProps) {
  const layerManager = useLayerManager();
  const [newLayerName, setNewLayerName] = useState('');
  const [showAddLayer, setShowAddLayer] = useState(false);

  const handleAddLayer = () => {
    if (!newLayerName.trim()) return;

    const id = `layer-${Date.now()}`;
    layerManager.createLayer(id, {
      name: newLayerName,
      visible: true,
      locked: false,
      opacity: 1,
      zIndex: layerManager.layers.length,
    });

    setNewLayerName('');
    setShowAddLayer(false);
  };

  const sortedLayers = [...layerManager.layers].sort((a, b) => b.zIndex - a.zIndex);

  return (
    <DropdownMenu>
      <DropdownMenuTrigger asChild>{trigger}</DropdownMenuTrigger>
      <DropdownMenuContent
        align="start"
        className="w-[320px] bg-neutral-800 border-neutral-700 p-0"
      >
        {/* Header */}
        <div className="flex items-center justify-between px-4 py-3 border-b border-neutral-700">
          <h3 className="text-sm font-semibold text-white">Layers</h3>
          <button
            onClick={() => setShowAddLayer(!showAddLayer)}
            className="p-1 hover:bg-neutral-700 rounded transition-colors"
            title="Add layer"
          >
            <Plus className="w-4 h-4 text-neutral-400" />
          </button>
        </div>

        {/* Add Layer Form */}
        {showAddLayer && (
          <div className="px-4 py-3 border-b border-neutral-700 space-y-2">
            <input
              type="text"
              value={newLayerName}
              onChange={e => setNewLayerName(e.target.value)}
              onKeyDown={e => e.key === 'Enter' && handleAddLayer()}
              placeholder="Layer name..."
              className="w-full px-2 py-1 text-sm bg-neutral-900 border border-neutral-600 rounded text-white placeholder-neutral-500 focus:outline-none focus:ring-1 focus:ring-blue-500"
              autoFocus
            />
            <div className="flex gap-2">
              <button
                onClick={handleAddLayer}
                className="flex-1 px-3 py-1 text-xs bg-blue-600 hover:bg-blue-700 text-white rounded transition-colors"
              >
                Add
              </button>
              <button
                onClick={() => {
                  setShowAddLayer(false);
                  setNewLayerName('');
                }}
                className="flex-1 px-3 py-1 text-xs bg-neutral-700 hover:bg-neutral-600 text-white rounded transition-colors"
              >
                Cancel
              </button>
            </div>
          </div>
        )}

        {/* Layer List */}
        <div className="max-h-[400px] overflow-y-auto">
          {/* Image Layer (Special) */}
          <div className="px-4 py-2 bg-neutral-900/50 border-b border-neutral-700">
            <div className="flex items-center gap-2">
              <button
                onClick={() => onImageVisibleChange?.(!imageVisible)}
                className="p-1 hover:bg-neutral-600 rounded transition-colors"
                title={imageVisible ? 'Hide image' : 'Show image'}
              >
                {imageVisible ? (
                  <Eye className="w-4 h-4 text-blue-400" />
                ) : (
                  <EyeOff className="w-4 h-4 text-neutral-500" />
                )}
              </button>
              <span className="flex-1 text-sm text-neutral-300 font-semibold">Image</span>
              <span className="text-xs text-neutral-500">Background</span>
            </div>
          </div>

          {/* Annotation Layers */}
          {sortedLayers.length === 0 ? (
            <div className="px-4 py-6 text-center text-sm text-neutral-500">
              No annotation layers
            </div>
          ) : (
            <div className="py-1">
              {sortedLayers.map(layer => {
                const isActive = activeLayerId === layer.id;
                return (
                  <div
                    key={layer.id}
                    className={`px-3 py-2 hover:bg-neutral-700/50 transition-colors group relative ${
                      isActive ? 'bg-green-900/30' : ''
                    }`}
                  >
                    {/* Active indicator bar on left */}
                    {isActive && (
                      <div className="absolute left-0 top-0 bottom-0 w-1 bg-green-500" />
                    )}

                    <div className="flex items-center gap-2 mb-2">
                      {/* Active Layer Indicator - Star icon */}
                      <button
                        onClick={() => onActiveLayerChange?.(layer.id)}
                        className="p-1 hover:bg-neutral-600 rounded transition-colors"
                        title={isActive ? 'Active layer' : 'Set as active layer'}
                      >
                        <Star
                          className={`w-4 h-4 ${
                            isActive
                              ? 'text-green-500 fill-green-500'
                              : 'text-neutral-600 hover:text-neutral-400'
                          }`}
                        />
                      </button>

                      {/* Visibility Toggle */}
                      <button
                        onClick={() => layerManager.setLayerVisibility(layer.id, !layer.visible)}
                        className="p-1 hover:bg-neutral-600 rounded transition-colors"
                        title={layer.visible ? 'Hide layer' : 'Show layer'}
                      >
                        {layer.visible ? (
                          <Eye className="w-4 h-4 text-blue-400" />
                        ) : (
                          <EyeOff className="w-4 h-4 text-neutral-500" />
                        )}
                      </button>

                      {/* Lock Toggle */}
                      <button
                        onClick={() => layerManager.setLayerLocked(layer.id, !layer.locked)}
                        className="p-1 hover:bg-neutral-600 rounded transition-colors"
                        title={layer.locked ? 'Unlock layer' : 'Lock layer'}
                      >
                        {layer.locked ? (
                          <Lock className="w-4 h-4 text-orange-400" />
                        ) : (
                          <Unlock className="w-4 h-4 text-neutral-500" />
                        )}
                      </button>

                      {/* Layer Name */}
                      <span
                        className={`flex-1 text-sm truncate ${isActive ? 'text-green-400 font-semibold' : 'text-white'}`}
                      >
                        {layer.name}
                      </span>

                      {/* Delete Button (only show for non-default layers) */}
                      {layer.id !== 'default' && (
                        <button
                          onClick={() => layerManager.deleteLayer(layer.id)}
                          className="p-1 opacity-0 group-hover:opacity-100 hover:bg-red-600/20 rounded transition-all"
                          title="Delete layer"
                        >
                          <X className="w-4 h-4 text-red-400" />
                        </button>
                      )}
                    </div>

                    {/* Opacity Slider */}
                    <div className="flex items-center gap-2 ml-10">
                      <span className="text-xs text-neutral-500 w-16">Opacity:</span>
                      <input
                        type="range"
                        min="0"
                        max="1"
                        step="0.1"
                        value={layer.opacity}
                        onChange={e =>
                          layerManager.setLayerOpacity(layer.id, parseFloat(e.target.value))
                        }
                        className="flex-1 h-1 bg-neutral-600 rounded-lg appearance-none cursor-pointer [&::-webkit-slider-thumb]:appearance-none [&::-webkit-slider-thumb]:w-3 [&::-webkit-slider-thumb]:h-3 [&::-webkit-slider-thumb]:bg-blue-500 [&::-webkit-slider-thumb]:rounded-full [&::-webkit-slider-thumb]:cursor-pointer"
                      />
                      <span className="text-xs text-neutral-400 w-8 text-right">
                        {Math.round(layer.opacity * 100)}%
                      </span>
                    </div>
                  </div>
                );
              })}
            </div>
          )}
        </div>
      </DropdownMenuContent>
    </DropdownMenu>
  );
}
