// docs/src/lib/components/ui/Tooltip.tsx
import React, { useState } from 'react';

export interface TooltipProps extends React.HTMLAttributes<HTMLDivElement> {
  content: string;
  children: React.ReactNode;
  side?: 'top' | 'right' | 'bottom' | 'left';
}

export const Tooltip = React.forwardRef<HTMLDivElement, TooltipProps>(
  ({ content, children, side = 'top', className, ...props }, ref) => {
    const [visible, setVisible] = useState(false);

    const getSideClasses = () => {
      switch (side) {
        case 'top':
          return 'bottom-full mb-2';
        case 'right':
          return 'left-full ml-2';
        case 'bottom':
          return 'top-full mt-2';
        case 'left':
          return 'right-full mr-2';
        default:
          return 'bottom-full mb-2';
      }
    };

    return (
      <div
        ref={ref}
        className="relative inline-block"
        onMouseEnter={() => setVisible(true)}
        onMouseLeave={() => setVisible(false)}
        {...props}
      >
        {children}
        {visible && (
          <div
            className={`absolute z-50 px-2 py-1 text-sm bg-slate-900 text-white rounded-md whitespace-nowrap ${getSideClasses()} ${className}`}
          >
            {content}
          </div>
        )}
      </div>
    );
  }
);

Tooltip.displayName = 'Tooltip';

// docs/src/lib/components/ui/tooltip.svelte
<script lang="ts">
  import type { Snippet } from "svelte";

  interface Props {
    text: string;
    children: Snippet;
    side?: "top" | "bottom" | "left" | "right";
  }

  let { text, children, side = "top" }: Props = $props();

  let visible = $state(false);
</script>

<div
  class="relative inline-block"
  onmouseenter={() => (visible = true)}
  onmouseleave={() => (visible = false)}
  role="tooltip"
>
  {@render children()}

  {#if visible}
    <div
      class="absolute z-50 px-2 py-1 text-xs text-white bg-slate-900 rounded shadow-lg whitespace-nowrap {side ===
      'top'
        ? 'bottom-full left-1/2 -translate-x-1/2 mb-2'
        : ''} {side === 'bottom'
        ? 'top-full left-1/2 -translate-x-1/2 mt-2'
        : ''}"
    >
      {text}
    </div>
  {/if}
</div>
